#!/usr/bin/env bash
#
# Generate gitignored Xcode signing settings from .env.local so local Debug
# and Release builds use the same Apple signing identity as release builds.
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env.local"
OUT_FILE="$ROOT_DIR/Signing.xcconfig"

[[ -f "$ENV_FILE" ]] || exit 0

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

SIGNING_IDENTITY="${PEEKBAR_SIGNING_IDENTITY:-${APPLE_SIGNING_IDENTITY:-}}"
[[ -n "$SIGNING_IDENTITY" ]] || exit 0

TEAM_ID="${PEEKBAR_DEVELOPMENT_TEAM:-${DEVELOPMENT_TEAM:-${APPLE_TEAM_ID:-}}}"

{
  cat <<EOF
// Generated by scripts/sync-local-signing.sh from .env.local.
// Local only. Do not commit.
CODE_SIGN_STYLE = Manual
CODE_SIGN_IDENTITY = $SIGNING_IDENTITY
EOF
  if [[ -n "$TEAM_ID" ]]; then
    echo "DEVELOPMENT_TEAM = $TEAM_ID"
  fi
} > "$OUT_FILE"
